name: mysql

instance_groups:
- name: arbitrator
  instances: 1
  azs: [az1]
  networks: 
  - name: CloudFoundry-10_119_68_0-22
    static_ips:
      - ((arbitrator-ip))
  vm_type: medium
  stemcell: default
  jobs:
  - {release: cf-mysql, name: arbitrator}

- name: backup
  instances: 1
  azs: [az1]
  networks: 
  - name: CloudFoundry-10_119_68_0-22
    static_ips:
      - ((backup-ip))
  vm_type: medium
  stemcell: default
  persistent_disk_type: medium
  jobs:
  - {release: cf-mysql, name: mysql}

- name: bootstrap
  instances: 1
  lifecycle: errand
  azs: [az1]
  networks: [{name: CloudFoundry-10_119_68_0-22}]
  vm_type: medium
  stemcell: default
  jobs:
  - {release: cf-mysql, name: bootstrap}

- name: rejoin-unsafe
  instances: 1
  lifecycle: errand
  azs: [az1]
  networks: [{name: CloudFoundry-10_119_68_0-22}]
  vm_type: medium
  stemcell: default
  jobs:
  - {release: cf-mysql, name: rejoin-unsafe}

- name: smoke-tests
  instances: 1
  lifecycle: errand
  azs: [az1]
  networks: [{name: CloudFoundry-10_119_68_0-22}]
  vm_type: medium
  stemcell: default
  jobs:
  - {release: cf-mysql, name: smoke-tests}
  properties:
    cf_mysql:
      smoke_tests:
        standalone_tests_only: true
