name: ((environment))cp-mysql

instance_groups:
- name: arbitrator
  instances: 1
  azs: [az1]
  networks: 
  - name: CloudFoundry-10_119_68_0-22
    static_ips:
      - ((arbitrator-ip))
  vm_type: medium
  stemcell: default
  jobs:
  - {release: cf-mysql, name: arbitrator}

- name: monitoring
  instances: 1
  azs: [az1]
  networks: 
  - name: CloudFoundry-10_119_68_0-22
    static_ips:
      - ((monitoring-ip))
  vm_type: medium
  stemcell: default
  jobs:
  - {release: cf-mysql, name: pmm-server}

- name: backup
  instances: 1
  azs: [az1]
  networks: 
  - name: CloudFoundry-10_119_68_0-22
    static_ips:
      - ((backup-ip))
  vm_type: medium
  stemcell: default
  persistent_disk_type: medium
  jobs:
  - {release: cf-mysql, name: mysql}

