resources:
- name: concourse-deploy-mysql
  type: git
  check_every: 4h
  source:
    uri: https://github.com/s-matyukevich/concourse-deploy-mysql
    branch: master
- name: mysql-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/cf-mysql-release
- name: vsphere-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
- name: control-plane-mysql
  type: bosh-deployment
  source:
    target: {{control-plane-bosh-url}}
    username: {{control-plane-bosh-user}}
    password: {{control-plane-bosh-password}}
    deployment: mysql
- name: scdc1-mysql
  type: bosh-deployment
  source:
    target: {{scdc1-bosh-url}}
    username: {{scdc1-bosh-user}}
    password: {{scdc1-bosh-password}}
    deployment: mysql
- name: wdc1-mysql
  type: bosh-deployment
  source:
    target: {{wdc1-bosh-url}}
    username: {{wdc1-bosh-user}}
    password: {{wdc1-bosh-password}}
    deployment: mysql

jobs:
- name: deploy-to-control-plane
  plan:
    - aggregate:
      - get: vsphere-stemcell
      - get: mysql-release
      - get: concourse-deploy-mysql
    - task: generate-manifest
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/bosh-worker
        run:
          path: concourse-deploy-mysql/ci/tasks/generate-manifest.sh concourse-deploy-mysql/ci/manifests/control-plane.yml
        params:
          ARBITRATOR_IP: {{arbitrator-ip}}
          SCDC1_MASTER_IP: {{scdc1-master-ip}}
          WCDC1_MASTER_IP: {{wdc1-master-ip}}
        inputs:
        - name: concourse-deploy-mysql
        outputs:
        - name: manifest
    - put: control-plane-mysql
      params:
        manifest: manifest/manifest.yml
- name: deploy-to-scdc1
  plan:
    - aggregate:
      - get: vsphere-stemcell
      - get: mysql-release
      - get: concourse-deploy-mysql
    - task: generate-manifest
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/bosh-worker
        run:
          path: concourse-deploy-mysql/ci/tasks/generate-manifest.sh concourse-deploy-mysql/ci/manifests/datacenter.yml
        params:
          ARBITRATOR_IP: {{arbitrator-ip}}
          SCDC1_MASTER_IP: {{scdc1-master-ip}}
          WCDC1_MASTER_IP: {{wdc1-master-ip}}
          MASTER_IP: {{scdc1-master-ip}}
          PROXY_IP: {{scdc1-proxy-ip}}
        inputs:
        - name: concourse-deploy-mysql
        outputs:
        - name: manifest
    - put: scdc1-mysql
      params:
        manifest: manifest/manifest.yml
- name: deploy-to-wdc1
  plan:
    - aggregate:
      - get: vsphere-stemcell
      - get: mysql-release
      - get: concourse-deploy-mysql
    - task: generate-manifest
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/bosh-worker
        run:
          path: concourse-deploy-mysql/ci/tasks/generate-manifest.sh concourse-deploy-mysql/ci/manifests/datacenter.yml
        params:
          ARBITRATOR_IP: {{arbitrator-ip}}
          SCDC1_MASTER_IP: {{scdc1-master-ip}}
          WCDC1_MASTER_IP: {{wdc1-master-ip}}
          MASTER_IP: {{wdc1-master-ip}}
          PROXY_IP: {{wdc1-proxy-ip}}
        inputs:
        - name: concourse-deploy-mysql
        outputs:
        - name: manifest
    - put: scdc1-wdc1
      params:
        manifest: manifest/manifest.yml
