resources:
- name: concourse-deploy-mysql
  type: git
  check_every: 4h
  source:
    uri: https://github.com/s-matyukevich/concourse-deploy-mysql
    branch: master
- name: vsphere-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent

jobs:
- name: upload-release-and-stemcell
  plan:
    - aggregate:
      - get: concourse-deploy-mysql
      - get: vsphere-stemcell
    - task: deploy
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/bosh-worker
        run:
          path: concourse-deploy-mysql/ci/tasks/upload-release.sh 
        params:
          VAULT_ADDR: {{vault-addr}}
          VAULT_TOKEN: {{vault-token}}
          CONTROL_PLANE_VAULT_PROPERTIES_PATH: {{control-plane-vault-properties-path}}
          SCDC1_VAULT_PROPERTIES_PATH: {{scdc1-vault-properties-path}}
          WDC1_VAULT_PROPERTIES_PATH: {{wdc1-vault-properties-path}}
          RELEASE_URL: {{release-url}}
        inputs:
        - name: concourse-deploy-mysql
        - name: vsphere-stemcell
- name: deploy-to-control-plane
  plan:
    - aggregate:
      - get: vsphere-stemcell
      - get: concourse-deploy-mysql
        passed: [deploy-to-wdc1]
    - task: deploy
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/bosh-worker
        run:
          path: concourse-deploy-mysql/ci/tasks/deploy.sh 
        params:
          MANIFEST: concourse-deploy-mysql/ci/manifests/control-plane.yml
          VAULT_ADDR: {{vault-addr}}
          VAULT_TOKEN: {{vault-token}}
          VAULT_PROPERTIES_PATH: {{control-plane-vault-properties-path}}
          ARBITRATOR_IP: {{arbitrator-ip}}
          BACKUP_IP: {{backup-ip}}
          SCDC1_MASTER_IPS: {{scdc1-master-ips}}
          WDC1_MASTER_IPS: {{wdc1-master-ips}}
          SCDC1_PROXY_IP: {{scdc1-proxy-ip}}
          WDC1_PROXY_IP: {{wdc1-proxy-ip}}
        inputs:
        - name: concourse-deploy-mysql
        - name: vsphere-stemcell
- name: deploy-to-scdc1
  plan:
    - aggregate:
      - get: vsphere-stemcell
      - get: concourse-deploy-mysql
        passed: [upload-release-and-stemcell]
    - task: deploy
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/bosh-worker
        run:
          path: concourse-deploy-mysql/ci/tasks/deploy.sh 
        params:
          MANIFEST: concourse-deploy-mysql/ci/manifests/scdc1.yml
          VAULT_ADDR: {{vault-addr}}
          VAULT_TOKEN: {{vault-token}}
          VAULT_PROPERTIES_PATH: {{scdc1-vault-properties-path}}
          ARBITRATOR_IP: {{arbitrator-ip}}
          BACKUP_IP: {{backup-ip}}
          SCDC1_MASTER_IPS: {{scdc1-master-ips}}
          WDC1_MASTER_IPS: {{wdc1-master-ips}}
          SCDC1_PROXY_IP: {{scdc1-proxy-ip}}
          WDC1_PROXY_IP: {{wdc1-proxy-ip}}
        inputs:
        - name: concourse-deploy-mysql
        - name: vsphere-stemcell
- name: deploy-to-wdc1
  plan:
    - aggregate:
      - get: vsphere-stemcell
      - get: concourse-deploy-mysql
        passed: [deploy-to-scdc1]
    - task: deploy
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/bosh-worker
        run:
          path: concourse-deploy-mysql/ci/tasks/deploy.sh 
        params:
          MANIFEST: concourse-deploy-mysql/ci/manifests/wdc1.yml
          VAULT_ADDR: {{vault-addr}}
          VAULT_TOKEN: {{vault-token}}
          VAULT_PROPERTIES_PATH: {{wdc1-vault-properties-path}}
          ARBITRATOR_IP: {{arbitrator-ip}}
          BACKUP_IP: {{backup-ip}}
          SCDC1_MASTER_IPS: {{scdc1-master-ips}}
          WDC1_MASTER_IPS: {{wdc1-master-ips}}
          SCDC1_PROXY_IP: {{scdc1-proxy-ip}}
          WDC1_PROXY_IP: {{wdc1-proxy-ip}}
        inputs:
        - name: concourse-deploy-mysql
        - name: vsphere-stemcell
- name: bootstrap
  plan:
    - aggregate:
      - get: concourse-deploy-mysql
    - task: bootstrap
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/bosh-worker
        run:
          path: concourse-deploy-mysql/ci/tasks/run-errand.sh
        params:
          BOSH_ERRAND: bootstrap
          VAULT_ADDR: {{vault-addr}}
          VAULT_TOKEN: {{vault-token}}
          VAULT_PROPERTIES_PATH: {{control-plane-vault-properties-path}}
        inputs:
        - name: concourse-deploy-mysql
- name: backup
  plan:
    - aggregate:
      - get: concourse-deploy-mysql
        passed: [deploy-to-control-plane]
    - task: bootstrap
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/bosh-worker
        run:
          path: concourse-deploy-mysql/ci/tasks/backup.sh
        params:
          VAULT_ADDR: {{vault-addr}}
          VAULT_TOKEN: {{vault-token}}
          VAULT_PROPERTIES_PATH: {{control-plane-vault-properties-path}}
        inputs:
        - name: concourse-deploy-mysql
- name: rejoin-unsafe
  plan:
    - aggregate:
      - get: concourse-deploy-mysql
    - task: rejoin-unsafe
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/bosh-worker
        run:
          path: concourse-deploy-mysql/ci/tasks/run-errand.sh
        params:
          BOSH_ERRAND: rejoin-unsafe
          VAULT_ADDR: {{vault-addr}}
          VAULT_TOKEN: {{vault-token}}
          VAULT_PROPERTIES_PATH: {{control-plane-vault-properties-path}}
        inputs:
        - name: concourse-deploy-mysql
        outputs:
- name: smoke-tests
  plan:
    - aggregate:
      - get: concourse-deploy-mysql
        passed: [deploy-to-control-plane]
    - task: smoke-tests
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/bosh-worker
        run:
          path: concourse-deploy-mysql/ci/tasks/run-errand.sh
        params:
          BOSH_ERRAND: smoke-tests
          VAULT_ADDR: {{vault-addr}}
          VAULT_TOKEN: {{vault-token}}
          VAULT_PROPERTIES_PATH: {{control-plane-vault-properties-path}}
        inputs:
        - name: concourse-deploy-mysql
