resources:
- name: concourse-deploy-mysql
  type: git
  source:
    uri: {{git-repo-url}}
    private_key: {{git-private-key}}
    branch: master
- name: vsphere-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent

jobs:
- name: upload-release-and-stemcell
  plan:
    - aggregate:
      - get: concourse-deploy-mysql
      - get: vsphere-stemcell
    - task: deploy
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/bosh-worker
        run:
          path: concourse-deploy-mysql/ci/tasks/upload-release.sh 
        params:
          VAULT_ADDR: {{vault-addr}}
          VAULT_TOKEN: {{vault-token}}
          CONTROL_PLANE_VAULT_PROPERTIES_PATH: {{control-plane-vault-properties-path}}
          SCDC1_VAULT_PROPERTIES_PATH: {{scdc1-vault-properties-path}}
          WDC1_VAULT_PROPERTIES_PATH: {{wdc1-vault-properties-path}}
          RELEASE_URL: {{release-url}}
          ENVIRONMENT: {{environment}}
        inputs:
        - name: concourse-deploy-mysql
        - name: vsphere-stemcell
- name: deploy-to-control-plane
  plan:
    - aggregate:
      - get: concourse-deploy-mysql
        # passed: [deploy-to-wdc1]
    - task: deploy
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/bosh-worker
        run:
          path: concourse-deploy-mysql/ci/tasks/deploy-control-plane.sh 
        params:
          MANIFEST: concourse-deploy-mysql/ci/manifests/control-plane.yml
          VAULT_ADDR: {{vault-addr}}
          VAULT_TOKEN: {{vault-token}}
          VAULT_PROPERTIES_PATH: {{control-plane-vault-properties-path}}
          ARBITRATOR_IP: {{arbitrator-ip}}
          BACKUP_IP: {{backup-ip}}
          SCDC1_MASTER_IPS: {{scdc1-master-ips}}
          WDC1_MASTER_IPS: {{wdc1-master-ips}}
          SCDC1_PROXY_IP: {{scdc1-proxy-ip}}
          WDC1_PROXY_IP: {{wdc1-proxy-ip}}
          SCDC1_BROKER_IP: {{scdc1-broker-ip}}
          WDC1_BROKER_IP: {{wdc1-broker-ip}}
          MONITORING_IP: {{monitoring-ip}}
          RELEASE_VERSION: {{release-version}}
          DEPLOYMENT: cp-mysql
          ENVIRONMENT: {{environment}}
        inputs:
        - name: concourse-deploy-mysql
- name: deploy-to-scdc1
  plan:
    - aggregate:
      - get: concourse-deploy-mysql
        # passed: [upload-release-and-stemcell]
    - task: deploy
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/bosh-worker
        run:
          path: concourse-deploy-mysql/ci/tasks/deploy.sh 
        params:
          MANIFEST: concourse-deploy-mysql/ci/manifests/scdc1.yml
          VAULT_ADDR: {{vault-addr}}
          VAULT_TOKEN: {{vault-token}}
          VAULT_PROPERTIES_PATH: {{scdc1-vault-properties-path}}
          VAULT_PASSWORDS_PATH: {{scdc1-vault-passwords-path}}
          ARBITRATOR_IP: {{arbitrator-ip}}
          BACKUP_IP: {{backup-ip}}
          SCDC1_MASTER_IPS: {{scdc1-master-ips}}
          WDC1_MASTER_IPS: {{wdc1-master-ips}}
          SCDC1_PROXY_IP: {{scdc1-proxy-ip}}
          WDC1_PROXY_IP: {{wdc1-proxy-ip}}
          SCDC1_BROKER_IP: {{scdc1-broker-ip}}
          WDC1_BROKER_IP: {{wdc1-broker-ip}}
          MONITORING_IP: {{monitoring-ip}}
          RELEASE_VERSION: {{release-version}}
          DEPLOYMENT: scdc1-mysql
          ENVIRONMENT: {{environment}}
        inputs:
        - name: concourse-deploy-mysql
    - task: register-broker		
      config:		
        platform: linux		
        image_resource:		
          type: docker-image		
          source:		
            repository: smatyukevich/bosh-worker		
        run:		
          path: concourse-deploy-mysql/ci/tasks/run-errand.sh		
        params:		
          BOSH_ERRAND: register-broker		
          VAULT_ADDR: {{vault-addr}}		
          VAULT_TOKEN: {{vault-token}}		
          VAULT_PROPERTIES_PATH: {{scdc1-vault-properties-path}}		
          DEPLOYMENT: scdc1-mysql
          ENVIRONMENT: {{environment}}
        inputs:		
        - name: concourse-deploy-mysql
- name: deploy-to-wdc1
  plan:
    - aggregate:
      - get: concourse-deploy-mysql
        # passed: [deploy-to-scdc1]
    - task: deploy
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/bosh-worker
        run:
          path: concourse-deploy-mysql/ci/tasks/deploy.sh 
        params:
          MANIFEST: concourse-deploy-mysql/ci/manifests/wdc1.yml
          VAULT_ADDR: {{vault-addr}}
          VAULT_TOKEN: {{vault-token}}
          VAULT_PROPERTIES_PATH: {{wdc1-vault-properties-path}}
          VAULT_PASSWORDS_PATH: {{wdc1-vault-passwords-path}}
          ARBITRATOR_IP: {{arbitrator-ip}}
          BACKUP_IP: {{backup-ip}}
          SCDC1_MASTER_IPS: {{scdc1-master-ips}}
          WDC1_MASTER_IPS: {{wdc1-master-ips}}
          SCDC1_PROXY_IP: {{scdc1-proxy-ip}}
          WDC1_PROXY_IP: {{wdc1-proxy-ip}}
          SCDC1_BROKER_IP: {{scdc1-broker-ip}}
          WDC1_BROKER_IP: {{wdc1-broker-ip}}
          MONITORING_IP: {{monitoring-ip}}
          RELEASE_VERSION: {{release-version}}
          DEPLOYMENT: wdc1-mysql
          ENVIRONMENT: {{environment}}
        inputs:
        - name: concourse-deploy-mysql
    - task: register-broker		
      config:		
        platform: linux		
        image_resource:		
          type: docker-image		
          source:		
            repository: smatyukevich/bosh-worker		
        run:		
          path: concourse-deploy-mysql/ci/tasks/run-errand.sh		
        params:		
          BOSH_ERRAND: register-broker		
          VAULT_ADDR: {{vault-addr}}		
          VAULT_TOKEN: {{vault-token}}		
          VAULT_PROPERTIES_PATH: {{wdc1-vault-properties-path}}		
          DEPLOYMENT: wdc1-mysql
          ENVIRONMENT: {{environment}}
        inputs:		
        - name: concourse-deploy-mysql
- name: backup
  plan:
    - aggregate:
      - get: concourse-deploy-mysql
        # passed: [deploy-to-control-plane]
    - task: bootstrap
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/bosh-worker
        run:
          path: concourse-deploy-mysql/ci/tasks/backup.sh
        params:
          VAULT_ADDR: {{vault-addr}}
          VAULT_TOKEN: {{vault-token}}
          VAULT_PROPERTIES_PATH: {{control-plane-vault-properties-path}}
          DEPLOYMENT: cp-mysql
          ENVIRONMENT: {{environment}}
        inputs:
        - name: concourse-deploy-mysql
