resources:
- name: concourse-deploy-mysql
  type: git
  check_every: 4h
  source:
    uri: https://github.com/s-matyukevich/concourse-deploy-mysql
    branch: master
- name: mysql-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/cf-mysql-release
- name: vsphere-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent

jobs:
- name: deploy-to-control-plane
  plan:
    - aggregate:
      - get: vsphere-stemcell
      - get: mysql-release
      - get: concourse-deploy-mysql
    - task: generate-manifest
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/bosh-worker
        run:
          path: concourse-deploy-mysql/ci/tasks/generate-manifest.sh 
        params:
          MANIFEST: concourse-deploy-mysql/ci/manifests/control-plane.yml
          VAULT_ADDR: {{vault-addr}}
          VAULT_TOKEN: {{vault-token}}
          VAULT_PROPERTIES_PATH: {{control-plane-vault-properties-path}}
          ARBITRATOR_IP: {{arbitrator-ip}}
          SCDC1_MASTER_IP: {{scdc1-master-ip}}
          WDC1_MASTER_IP: {{wdc1-master-ip}}
          SCDC1_PROXY_IP: {{scdc1-proxy-ip}}
          WDC1_PROXY_IP: {{wdc1-proxy-ip}}
        inputs:
        - name: concourse-deploy-mysql
- name: deploy-to-scdc1
  plan:
    - aggregate:
      - get: vsphere-stemcell
      - get: mysql-release
      - get: concourse-deploy-mysql
    - task: generate-manifest
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/bosh-worker
        run:
          path: concourse-deploy-mysql/ci/tasks/generate-manifest.sh 
        params:
          MANIFEST: concourse-deploy-mysql/ci/manifests/scdc1.yml
          VAULT_ADDR: {{vault-addr}}
          VAULT_TOKEN: {{vault-token}}
          VAULT_PROPERTIES_PATH: {{scdc1-vault-properties-path}}
          ARBITRATOR_IP: {{arbitrator-ip}}
          SCDC1_MASTER_IP: {{scdc1-master-ip}}
          WDC1_MASTER_IP: {{wdc1-master-ip}}
          SCDC1_PROXY_IP: {{scdc1-proxy-ip}}
          WDC1_PROXY_IP: {{wdc1-proxy-ip}}
        inputs:
        - name: concourse-deploy-mysql
        outputs:
        - name: manifest
- name: deploy-to-wdc1
  plan:
    - aggregate:
      - get: vsphere-stemcell
      - get: mysql-release
      - get: concourse-deploy-mysql
    - task: generate-manifest
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/bosh-worker
        run:
          path: concourse-deploy-mysql/ci/tasks/generate-manifest.sh 
        params:
          MANIFEST: concourse-deploy-mysql/ci/manifests/wdc1.yml
          VAULT_ADDR: {{vault-addr}}
          VAULT_TOKEN: {{vault-token}}
          VAULT_PROPERTIES_PATH: {{wdc1-vault-properties-path}}
          ARBITRATOR_IP: {{arbitrator-ip}}
          SCDC1_MASTER_IP: {{scdc1-master-ip}}
          WDC1_MASTER_IP: {{wdc1-master-ip}}
          SCDC1_PROXY_IP: {{scdc1-proxy-ip}}
          WDC1_PROXY_IP: {{wdc1-proxy-ip}}
        inputs:
        - name: concourse-deploy-mysql
        outputs:
        - name: manifest
- name: bootstrap
  plan:
    - aggregate:
      - get: concourse-deploy-mysql
    - task: bootstrap
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/bosh-worker
        run:
          path: concourse-deploy-mysql/ci/tasks/run-errand.sh
        params:
          BOSH_ERRAND: bootstrap
          VAULT_ADDR: {{vault-addr}}
          VAULT_TOKEN: {{vault-token}}
          VAULT_PROPERTIES_PATH: {{control-plane-vault-properties-path}}
        inputs:
        - name: concourse-deploy-mysql
        outputs:
- name: rejoin-unsafe
  plan:
    - aggregate:
      - get: concourse-deploy-mysql
    - task: rejoin-unsafe
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/bosh-worker
        run:
          path: concourse-deploy-mysql/ci/tasks/run-errand.sh
        params:
          BOSH_ERRAND: rejoin-unsafe
          VAULT_ADDR: {{vault-addr}}
          VAULT_TOKEN: {{vault-token}}
          VAULT_PROPERTIES_PATH: {{control-plane-vault-properties-path}}
        inputs:
        - name: concourse-deploy-mysql
        outputs:
- name: smoke-tests
  plan:
    - aggregate:
      - get: concourse-deploy-mysql
    - task: smoke-tests
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/bosh-worker
        run:
          path: concourse-deploy-mysql/ci/tasks/run-errand.sh
        params:
          BOSH_ERRAND: smoke-tests
          VAULT_ADDR: {{vault-addr}}
          VAULT_TOKEN: {{vault-token}}
          VAULT_PROPERTIES_PATH: {{control-plane-vault-properties-path}}
        inputs:
        - name: concourse-deploy-mysql
        outputs:
